name: AndroidBuild
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      
      - name: Setup Java JDK
        uses: actions/setup-java@v4.3.0
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: gradle

      - name: Cache Gradle files
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','**/graddle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Decrypt keystore
        run: |
          echo "${{ secrets.MYAPP_RELEASE_STOREFILE }}" > my-release-key.jks
        env:
          MYAPP_RELEASE_STOREFILE: ${{ secrets.MYAPP_RELEASE_STOREFILE }}
          
      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: release-apk
          path: app/release/release.apk
            

      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.API_KEY }}
      #   with:
      #     tag_name: release-${{ github.run_number }}
      #     release_name: Release ${{ github.run_number }}
      #     draft: flase
      #     prerelease: false

      # - name: Upload APK to release
      #   uses: actions/upload-release-asset@v1
      #   env: 
      #     GITHUB_TOKEN: ${{ secrets.API_KEY }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: app/release/app-release.apk
      #     asset_name: app-release.apk
      #     asset_content_type: application/vnd.android.package-archive
