name: AndroidBuild
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: permission
        run: chmod +x gradlew

      - name: Decoding keystore
        run: echo "${{ secrets.MYAPP_RELEASE_STORE_FILE }}" | base64 --decode > android_keystore.jks
        shell: bash
        
      - name: Build with Gradle
        run: ./gradlew assembleRelease
        env:
          ANDROID_KEYSTORE: android_keystore.jks
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.MYAPP_RELEASE_STORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.MYAPP_RELEASE_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.MYAPP_RELEASE_KEY_PASSWORD }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "Release"
          path: app/build/outputs/apk/release/*.apk
          if-no-files-found: error
            

      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.API_KEY }}
      #   with:
      #     tag_name: release-${{ github.run_number }}
      #     release_name: MemoryGame ${{ github.run_number }}
      #     draft: false
      #     prerelease: false

      # - name: Upload APK to release
      #   uses: actions/upload-release-asset@v1
        # env: 
        #   GITHUB_TOKEN: ${{ secrets.API_KEY }}
        # with:
        #   upload_url: ${{ steps.create_release.outputs.upload_url }}
        #   asset_path: app/build/outputs/apk/release/app-release.apk
        #   asset_name: MemoryGame.apk
        #   asset_content_type: application/vnd.android.package-archive
