name: AndroidBuild
on:
  pull_request: 
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.2
        with:
          java-version: '17'
          distribution: 'adopt'
        
      - name: Build with Gradle
        run: ./gradlew build

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.API_KEY }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: flase
          prerelease: false

      - name: Upload APK to release
        uses: actions/upload-release-asset@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.API_KEY }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/release/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
